### ISSUE TITLE
Exit code 139 (seg fault) when trying to set beam width parameter (-beam) on Ubuntu 15.10

### ISSUE THREAD

**Issue by khtad** [cmusphinx/pocketsphinx-python#10]
I noticed that there isn't a SWIG usage to configure the beam width in ~/pocketsphinx-python/pocketsphinx/swig/python/pocketsphinx.pypocketsphinx.py. Is there another way to change the beam-width? I'm getting overpruning at 1.0-e48 with my JSGF application and it's causing me to lose commands. Those commands also break in the c implementation at 1.0e-48, but work just fine at 1.0e-64.

**Comment by mbait** [comment]
> ~/pocketsphinx-python/pocketsphinx/swig/python/pocketsphinx.pypocketsphinx.py

What kind of path is that? Totally confusing. You can change whatever parameter you want using `Config#set_type()` methods, i.e. `config.set_float('-beam', 1e-64)`. Please elaborate on segfault. How do you set the beam so it causes a segfault? What code do you run? What's the output? Thank you!
