### ISSUE TITLE
Pip install results in Error

### ISSUE THREAD

**Issue by KarthikShivaa** [cmusphinx/pocketsphinx-python#11]
Unable to find Vcvarsall.bat - Pip (Windows 10) I have satisfied all dependancies

And i am unable to download setup.py n related files.... Doesnt download completely.. the file dowloaded is just 7kb zip file

**Comment by nshmyrev** [comment]
This problem is widely covered in the Internet. You need to install Microsoft Compiler For Python from here: 

https://www.microsoft.com/en-us/download/details.aspx?id=44266
