### ISSUE TITLE
Compiling pocketsphinx for Python 3.5

### ISSUE THREAD

**Issue by rcbyron** [cmusphinx/pocketsphinx-python#12]
I'm struggling to find an easy way to compile this extension on Windows 10 for Python 3.5
The only compiler I've gotten to work (VS 2015 Express) involves a lengthy download/install.
I would like my users to have an easier/quicker way to install this dependency.

Is there a better VS compiler than "VS 2015 Express" for Python 3.5 that I can use?

Also, are there plans to make this a pre-compiled package so users don't have to go through the trouble of SWIG and MS Visual Studio? I would like to help make that happen. Maybe you could point me in the right direction?

Thanks in advance,
Connor

**Comment by Uberi** [comment]
Hey @rcbyron,

I've got some relatively recent Windows builds over [here](https://github.com/Uberi/speech_recognition/tree/master/third-party), as wheel packages for Python 2.7, 3.4, and 3.5.

They're not "official", but I've tested them and they work on 64-bit Windows 7, Windows 8.1, and Windows 10.

**Comment by rcbyron** [comment]
For anyone still looking, here is a compiled build for windows: http://www.lfd.uci.edu/~gohlke/pythonlibs/#pocketsphinx

Christoph Gohlke kindly added this to his unofficial library, upon request.

**Comment by ChrisMuir** [comment]
Thank you @rcbyron for posting the compiled build, this was super helpful for me (using Windows 10 with Python 3.6).
