### ISSUE TITLE
Example program -Error

### ISSUE THREAD

**Issue by KarthikShivaa** [cmusphinx/pocketsphinx-python#14]
Please tell me how to correct this error.... 
Thanks in advance!
Traceback (most recent call last):
  File "/home/user/PycharmProjects/untitled/zen.py", line 9, in <module>
    config = Decoder.default_config()
NameError: name 'Decoder' is not defined

Process finished with exit code 1

**Comment by nshmyrev** [comment]
import pocketsphinx module properly.

**Comment by TobiasWeis** [comment]
I just did a fresh clone and built it, and the example program (which is provided by you and untouched) only throws errors. First ones in line are actually:
Traceback (most recent call last):
  File "./example.py", line 4, in <module>
    from pocketsphinx.pocketsphinx import *
ImportError: No module named pocketsphinx

After one removes the first pocketsphinx and the first sphinxbase, the Decoder-Error from above comes.

**Comment by nshmyrev** [comment]
You can check files in your filesystem and installation log to see if module is actually properly installed. Most likely it was not installed properly. To get further help you need to provide installation logs.

**Comment by TobiasWeis** [comment]
Again, this is related to the false instructions in the readme. Still had the repo-version installed. After uninstalling that, building fresh from git, the example works.

**Comment by mbait** [comment]
What readme are you referring to and what instructions do you consider
"false"?

On Thu, Apr 28, 2016 at 4:42 PM, Tobi notifications@github.com wrote:

> Again, this is related to the false instructions in the readme. Still had
> the repo-version installed. After uninstalling that, building fresh from
> git, the example works.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cmusphinx/pocketsphinx-python/issues/14#issuecomment-215594190

## 

Sincerely, Alexander

**Comment by TobiasWeis** [comment]
Regarding the readme, please excuse, fault was totally on my side (surprise!), it got too late last night. I misread the readme and installed with apt-get (this package in the repos seems to be broken?) instead of pip/git.
