### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by TobiasWeis** [cmusphinx/pocketsphinx-python#15]
When trying to run the basic usage example shown in the readme, it throws an error already on importing: 

from pocketsphinx.pocketsphinx import *
  File "sphinxbase.pxd", line 150, in init pocketsphinx (pocketsphinx.c:7935)
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object

-- has been installed from the repos (Ubuntu 14.04),
pip version info:
## pip show pocketsphinx

Name: PocketSphinx
Version: 0.8
Location: /usr/lib/python2.7/dist-packages

**Comment by mbait** [comment]
That is the outdated version, you should install pocketsphinx manually -
https://github.com/cmusphinx/pocketsphinx-python

On Thu, Apr 28, 2016 at 2:48 PM, Tobi notifications@github.com wrote:

> When trying to run the basic usage example shown in the readme, it throws
> an error already on importing:
> 
> from pocketsphinx.pocketsphinx import *
> File "sphinxbase.pxd", line 150, in init pocketsphinx (pocketsphinx.c:7935)
> ValueError: PyCapsule_GetPointer called with invalid PyCapsule object
> 
> -- has been installed from the repos (Ubuntu 14.04),
> pip version info:
> pip show pocketsphinx
> 
> Name: PocketSphinx
> Version: 0.8
> Location: /usr/lib/python2.7/dist-packages
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cmusphinx/pocketsphinx-python/issues/15

## 

Sincerely, Alexander

**Comment by TobiasWeis** [comment]
Well then I think it would be cool to change the Readme, I am sure more people have that error as long as the package in the repos is outdated. An unrelated question (sorry for that): is there a way to use this python-module to perform continuous speech recog?

**Comment by nshmyrev** [comment]
https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/continuous_test.py

**Comment by TobiasWeis** [comment]
What is your suggestion on using actual microphone input? What sample-rate, etc.? Is there some code or clear explanation for that?

**Comment by nshmyrev** [comment]
```
import pyaudio
p = pyaudio.PyAudio()
stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True)
stream.start_stream()
```

**Comment by TobiasWeis** [comment]
Thanks a lot! Got it to work!

**Comment by TobiasWeis** [comment]
And regarding the readme, please excuse, fault was totally on my side (surprise!), it got too late last night. I misread the readme and installed with apt-get (this package in the repos seems to be broken?) instead of pip/git.

**Comment by nshmyrev** [comment]
No problem, let us know if you have any issues.
