### ISSUE TITLE
Error while importing pocketsphinx

### ISSUE THREAD

**Issue by pdoongarwal** [cmusphinx/pocketsphinx-python#18]
I have installed pocketsphinx but not able to import the module.
I am using Ubuntu 16.04.

```
sudo -H pip install pocketsphinx        
Requirement already satisfied (use --upgrade to upgrade): pocketsphinx in /usr/local/lib/python2.7/dist-packages/pocketsphinx-0.1.0-py2.7-linux-x86_64.egg
```

```
>>> from pocketsphinx.pocketsphinx import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx-0.1.0-py2.7-linux-x86_64.egg/pocketsphinx/__init__.py", line 32, in <module>
    from .pocketsphinx import *
ImportError: No module named pocketsphinx
```

Is the module not compatible with Ubuntu 16.04?

**Comment by nshmyrev** [comment]
To debug import errors you can run `python -v -m test.py`, see http://stackoverflow.com/questions/7332299/trace-python-imports

**Comment by Pankaj-Baranwal** [comment]
I was facing the same problem.
The solution I found was simply to follow the instructions on terminal:
`sudo -H pip install --upgrade pocketsphinx`
After this, I was successfully able to execute the python script

**Comment by gurjarr587** [comment]
It depends on your python version so just make sure you have pip installed by the way I did this for python 3.x:
sudo -H pip3 install --upgrade pocketsphinx

**Comment by wahyubram82** [comment]
try to looking what kind of function that can be import from pocketsphinx module.

simple just do like this:

```
import pocketsphinx
dir(pocketsphinx)
help(pocketsphinx)
```
by do this you will saw all packet from pocketsphinx and you will get a conclucion, is there any package named pocketsphinx from pocketsphinx module.
