### ISSUE TITLE
Size of audio file in bytes to read

### ISSUE THREAD

**Issue by novitoll** [cmusphinx/pocketsphinx-python#19]
Hello,

Could you please tell if the window which is defined by `buf = stream.read(args.chunk_size)` in my script below affect on recognition? `307200` is 300 Kbytes of approximately ~ 10 sec of .wav, PCM signed 16-bit little endian, 16 KHz sample rate. So how is window of utterance defined? I guess this is called Hamming window (Error-correction code). My audio file is [this video](https://www.youtube.com/watch?v=AOoP56eXtzM) which I convert using `ffmpeg` to .wav format with settings above. Thanks in advance

P.S.: With 300 Kbytes of file size to read, I got

```
WRR: 45.000000 % (       195 /        424)
WER: 58.000000 % (       249 /        424)
``` 

with 1024 bytes, I got

```
WRR: 9.000000 % (        41 /        424)
WER: 103.000000 % (       440 /        424)
```

```python
#!/usr/bin/env python
import datetime
import os
import glob
import argparse

from pocketsphinx.pocketsphinx import Decoder

DEFAULT_MODEL_PATH = '/usr/local/share/pocketsphinx/model/en-us'
DEFAULT_CHUNK_SIZE = 307200  # ~ 10 sec of .wav, PCM signed 16-bit little endian, 16 KHz sample rate, mono channel
buzz_words = ['<s>', '</s>', '[SPEECH]', '[NOISE]', '<sil>']

hypothesis = []
bag_of_words = []
decoder = None


def main(args):
    # read audio files from directory
    if args.indir:
        audio_filepaths = [glob.glob(e) for e in ['*.wav', '*.raw']]
        if not audio_filepaths:
            print 'No audio file (.wav, .raw) in given directory was found.'
            return
        for f in audio_filepaths:
            recognize_audio(f, args)
    # read given single audio file
    elif args.infile:
        recognize_audio(args.infile, args)

    # write hypothesis into the separate file, joining with empty space
    f = open(os.path.join(os.getcwd(), 'leo', 'recognized_sphinx_%s.txt' % args.chunk_size), 'w+')
    f.write(' '.join(hypothesis))
    f.close()

    # write segments into separate file
    # TODO: further work with segments
    f = open(os.path.join(os.getcwd(), 'leo', 'recognized_sphinx_%s_segments.txt' % args.chunk_size), 'w+')
    [f.write('%s\n' % s) for s in bag_of_words]
    f.close()


def recognize_audio(audio_file, args):
    try:
        decoder.start_utt()
        stream = open(audio_file, 'rb')
        while True:
            buf = stream.read(args.chunk_size)
            if buf:
                decoder.process_raw(buf, False, False)
            else:
                break
            if decoder.hyp() is not None:
                hypothesis.append(decoder.hyp().hypstr)
                [bag_of_words.append(seg.word) for seg in decoder.seg() if seg.word not in buzz_words]
                decoder.end_utt()
                decoder.start_utt()
    except Exception, ex:
        print 'Error occurred with %s \n%s' % (audio_file, ex)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-infile', help='Audio .wav/.raw file')
    parser.add_argument('-indir', help='Directory containing audio files', nargs='?')
    parser.add_argument('-chunk_size', help='Size of audio file in bytes to read', default=DEFAULT_CHUNK_SIZE, type=int)
    parser.add_argument('-hmm', help='Acoustic model directory', default=os.path.join(DEFAULT_MODEL_PATH, 'en-us'))
    parser.add_argument('-lm', help='Language model input file', default=os.path.join(DEFAULT_MODEL_PATH, 'en-us.lm.bin'))
    parser.add_argument('-dict', help='Pronunciation dictionary input file', default=os.path.join(DEFAULT_MODEL_PATH, 'cmudict-en-us.dict'))

    args = parser.parse_args()

    # Create a decoder with certain model
    config = Decoder.default_config()
    config.set_string('-hmm', args.hmm)
    config.set_string('-lm', args.lm)
    config.set_string('-dict', args.dict)
    config.set_string('-logfn', os.path.join(os.getcwd(), 'results-%s.log' % datetime.datetime.now()))

    decoder = Decoder(config)

    main(args)
```

**Comment by novitoll** [comment]
So, I'm assuming that I don't need to train any Language Model or fill dictionary, as my current focus is to understand how it works with pre-built models.. Only things I'd like to tune is probably Feature Extraction part and perhaps Acoustic Model.

I had a chance to play around with the same audio file using Google Speech API, Microsoft Cognitive Services - Bing Speech API, and IBM Watson via online service.

So Google API offers sync and async API with 1 min and 80 mins audio file duration limit respectively. And Microsoft's limit is 10 sec per each file. And I split my full audio (3:12) into N-parts per 10 sec using ffmpeg, and with `pocketsphinx_continuous` utility I got worse results than using the same params via same utility but using 1 entire audio file. So question is - how does pocketsphinx get the utterance? 

From [this paper](http://mi.eng.cam.ac.uk/~mjfg/mjfg_NOW.pdf), I got that 

> Feature vectors are typically computed every 10 ms using an overlapping analysis window of around 25 ms

I'm not worried too much about accuracy, because eventually I will maybe use Kaldi :) But would like to understand Sphinx first as it is great toolkit to start (appreciate you, guys).

This is probably some Quora question, but please suggest if my understanding of this is correct and if I'm going right direction on the way of understanding SR. Thanks again.

**Comment by nshmyrev** [comment]
> def recognize_audio(audio_file, args):

This code is not correct. It is good for processing the audio at once, but not for audio chunks going one by one because you restart after first word is recognized and chunks are processed independently, not continuously. Continuous processing example with VAD is here:

https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/continuous_test.py

> And I split my full audio (3:12) into N-parts per 10 sec using ffmpeg, and with pocketsphinx_continuous utility I got worse results than using the same params via same utility but using 1 entire audio file. 

Recognizer needs few second to estimate channel parameters (CMN), for that reason it is better to process audio continuously without restarts. Alternative is batch processing when audio parameters are estimated from the whole utterance at once. There is full_utt parameter in ps_process_raw to perform batch processing.

**Comment by novitoll** [comment]
> it is better to process audio continuously without restarts

Ok, thanks, so I tried with this code below, see I start utterance only once here.

So does this [1024](https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/continuous_test.py#L24) mean that 1024 bytes of audio are read separately in loop, and Decoder works only with this 1024 bytes chunk? I mean, there is no information whether this chunk has the full utterance or it can be chunked abruptly. Is it the same as `pocketsphinx_continuous` work? Does it use 1024 bytes too?

``` python
def recognize_audio(audio_file, args):
    try:
        decoder.start_utt()
        stream = open(audio_file, 'rb')
        in_speech_bf = False
        while True:
            buf = stream.read(args.chunk_size)
            if buf:
                decoder.process_raw(buf, False, False)  # full_utt - False
                if decoder.get_in_speech() != in_speech_bf:
                    in_speech_bf = decoder.get_in_speech()
                    if decoder.hyp() is not None:
                        # decoder.end_utt()
                        hypothesis.append(decoder.hyp().hypstr)
                        # decoder.start_utt()
            else:
                break
    except Exception, ex:
        print 'Error occurred with %s \n%s' % (audio_file, ex)
```

**Comment by nshmyrev** [comment]
> Ok, thanks, so I tried with this code below, see I start utterance only once here.

It is a bad idea to modify example without understanding. Original code is correct, your modification is wrong.

> So does this 1024 mean that 1024 bytes of audio are read separately in loop, and Decoder works only with this 1024 bytes chunk?

Decoder remembers previously processed audio since start_utt

> I mean, there is no information whether this chunk has the full utterance or it can be chunked abruptly.

chunks are not full utterances since full_utt is false.

> Is it the same as pocketsphinx_continuous work? 

Yes

> Does it use 1024 bytes too?

It uses 4096
