### ISSUE TITLE
config.h and sphinx_config.h not included in path

### ISSUE THREAD

**Issue by gdbassett** [cmusphinx/pocketsphinx-python#2]
config.h and sphinx_config.h from the pocketsphinx-python/include directory are not included in the build path for the recursively-acquired sphinxbase causing it's build to fail.  This is on OS X 10.10.4 with python 2.7.9 from homebrew.

Work around: Include the libraries manually. `pip install pocketsphinx --global-option=build_ext --global-option="-I./pocketsphinx-python/include" (Requires cloning the code)

**Comment by triiiiista** [comment]
Works perfect. Thanks.

**Comment by nshmyrev** [comment]
This was fixed quite some time ago
