### ISSUE TITLE
pocketsphinx-python Raspberry pi 3

### ISSUE THREAD

**Issue by lihp123** [cmusphinx/pocketsphinx-python#20]
Hey
Someone an idea how to get this running on a Raspberry  Pi 3?
Right now i am getting the error "SIZEOF_LONG" redefined...

**Comment by nshmyrev** [comment]
Provide a complete compiler output and more information about what you are doing first.

**Comment by lihp123** [comment]
Hello again,
Using a Raspberry Pi 3  B.
I followed the installation instruction on http://cmusphinx.sourceforge.net/wiki/tutorialpocketsphinx
Command 'pocketsphinx_continuous -inmic yes' does work.
But when i try to install pocketsphinx using 'sudo pip install pocketsphinx' or 'pip install pocketsphinx' i get this error:

Collecting pocketsphinx
  Using cached pocketsphinx-0.1.3.zip
Building wheels for collected packages: pocketsphinx
  Running setup.py bdist_wheel for pocketsphinx ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZGW4Dg/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpBmG1kepip-wheel- --python-tag cp27:
  running bdist_wheel
  running build_ext
  building 'sphinxbase._ad' extension
  swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
  swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
  creating build
  creating build/temp.linux-armv7l-2.7
  creating build/temp.linux-armv7l-2.7/swig
  creating build/temp.linux-armv7l-2.7/swig/sphinxbase
  creating build/temp.linux-armv7l-2.7/deps
  creating build/temp.linux-armv7l-2.7/deps/sphinxbase
  creating build/temp.linux-armv7l-2.7/deps/sphinxbase/src
  creating build/temp.linux-armv7l-2.7/deps/sphinxbase/src/libsphinxad
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python2.7 -c swig/sphinxbase/ad_wrap.c -o build/temp.linux-armv7l-2.7/swig/sphinxbase/ad_wrap.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
  In file included from deps/sphinxbase/include/sphinxbase/ad.h:44:0,
                   from swig/sphinxbase/ad_wrap.c:2958:
  deps/sphinxbase/include/android/sphinx_config.h:11:0: warning: "SIZEOF_LONG" redefined
   #define SIZEOF_LONG 8
   ^
  In file included from /usr/include/python2.7/pyconfig.h:13:0,
                   from /usr/include/python2.7/Python.h:8,
                   from swig/sphinxbase/ad_wrap.c:130:
  /usr/include/arm-linux-gnueabihf/python2.7/pyconfig.h:1013:0: note: this is the location of the previous definition
   #define SIZEOF_LONG 4
   ^
  cc1: warning: unrecognized command line option "-Wno-misleading-indentation"
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python2.7 -c deps/sphinxbase/src/libsphinxad/ad_pulse.c -o build/temp.linux-armv7l-2.7/deps/sphinxbase/src/libsphinxad/ad_pulse.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
  deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:30: fatal error: pulse/pulseaudio.h: No such file or directory
   #include <pulse/pulseaudio.h>
                                ^
  compilation terminated.
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pocketsphinx
  Running setup.py clean for pocketsphinx
Failed to build pocketsphinx
Installing collected packages: pocketsphinx
  Running setup.py install for pocketsphinx ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZGW4Dg/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-KG77Vz-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building 'sphinxbase._ad' extension
    swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
    swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
    creating build
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/swig
    creating build/temp.linux-armv7l-2.7/swig/sphinxbase
    creating build/temp.linux-armv7l-2.7/deps
    creating build/temp.linux-armv7l-2.7/deps/sphinxbase
    creating build/temp.linux-armv7l-2.7/deps/sphinxbase/src
    creating build/temp.linux-armv7l-2.7/deps/sphinxbase/src/libsphinxad
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python2.7 -c swig/sphinxbase/ad_wrap.c -o build/temp.linux-armv7l-2.7/swig/sphinxbase/ad_wrap.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
    In file included from deps/sphinxbase/include/sphinxbase/ad.h:44:0,
                     from swig/sphinxbase/ad_wrap.c:2958:
    deps/sphinxbase/include/android/sphinx_config.h:11:0: warning: "SIZEOF_LONG" redefined
     #define SIZEOF_LONG 8
     ^
    In file included from /usr/include/python2.7/pyconfig.h:13:0,
                     from /usr/include/python2.7/Python.h:8,
                     from swig/sphinxbase/ad_wrap.c:130:
    /usr/include/arm-linux-gnueabihf/python2.7/pyconfig.h:1013:0: note: this is the location of the previous definition
     #define SIZEOF_LONG 4
     ^
    cc1: warning: unrecognized command line option "-Wno-misleading-indentation"
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python2.7 -c deps/sphinxbase/src/libsphinxad/ad_pulse.c -o build/temp.linux-armv7l-2.7/deps/sphinxbase/src/libsphinxad/ad_pulse.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
    deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:30: fatal error: pulse/pulseaudio.h: No such file or directory
     #include <pulse/pulseaudio.h>
                                  ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZGW4Dg/pocketsphinx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-KG77Vz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ZGW4Dg/pocketsphinx/


any idea what i did wrong? Thanks a lot in advance!!!

**Comment by lihp123** [comment]
Pulseaudio is installed and up-to-date
and i used the newest pocketsphinx and sphinxbase from https://github.com/cmusphinx

**Comment by lihp123** [comment]
using ' git clone --recursive https://github.com/bambocher/pocketsphinx-python' and 'sudo python setup.py install' i get this error:

running install
running build_ext
building 'sphinxbase._ad' extension
swigging swig/sphinxbase/ad.i to swig/sphinxbase/ad_wrap.c
swig -python -modern -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -Ideps/sphinxbase/swig -outdir sphinxbase -o swig/sphinxbase/ad_wrap.c swig/sphinxbase/ad.i
creating build
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/swig
creating build/temp.linux-armv7l-2.7/swig/sphinxbase
creating build/temp.linux-armv7l-2.7/deps
creating build/temp.linux-armv7l-2.7/deps/sphinxbase
creating build/temp.linux-armv7l-2.7/deps/sphinxbase/src
creating build/temp.linux-armv7l-2.7/deps/sphinxbase/src/libsphinxad
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python2.7 -c swig/sphinxbase/ad_wrap.c -o build/temp.linux-armv7l-2.7/swig/sphinxbase/ad_wrap.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
In file included from deps/sphinxbase/include/sphinxbase/ad.h:44:0,
                 from swig/sphinxbase/ad_wrap.c:2958:
deps/sphinxbase/include/android/sphinx_config.h:11:0: warning: "SIZEOF_LONG" redefined
 #define SIZEOF_LONG 8
 ^
In file included from /usr/include/python2.7/pyconfig.h:13:0,
                 from /usr/include/python2.7/Python.h:8,
                 from swig/sphinxbase/ad_wrap.c:130:
/usr/include/arm-linux-gnueabihf/python2.7/pyconfig.h:1013:0: note: this is the location of the previous definition
 #define SIZEOF_LONG 4
 ^
cc1: warning: unrecognized command line option "-Wno-misleading-indentation"
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python2.7 -c deps/sphinxbase/src/libsphinxad/ad_pulse.c -o build/temp.linux-armv7l-2.7/deps/sphinxbase/src/libsphinxad/ad_pulse.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:30: fatal error: pulse/pulseaudio.h: No such file or directory
 #include <pulse/pulseaudio.h>
                              ^
compilation terminated.
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1




sorry, dont wanna spam

**Comment by lihp123** [comment]
okay, nevermind....
after 15 hours i realised i was just missing libpulse-dev

**Comment by nshmyrev** [comment]
Ok, congratulations
