### ISSUE TITLE
Converting frame into seconds

### ISSUE THREAD

**Issue by dieka13** [cmusphinx/pocketsphinx-python#24]
I got start and end frame using:
`result = [{'word': seg.word, 'begin': seg.start_frame, 'end': seg.end_frame} for seg in decoder.seg()]`

now i want begin and end in second, how do i do that?

**Comment by nshmyrev** [comment]
Divide by 100

**Comment by dieka13** [comment]
I just do that and found out that the starting second always equal to length of audio + first detected word time. so i find min of start_frame and distract every start_frame and end_frame time to get the accurate second
