### ISSUE TITLE
ImportError: No module named pocketsphinx

### ISSUE THREAD

**Issue by dnyanesh-dev-repo** [cmusphinx/pocketsphinx-python#28]
Hi,

I have installed library from link: https://github.com/cmusphinx/pocketsphinx-python 

I got below exception 
[
Traceback (most recent call last):
File "example.py", line 3, in <module>
from pocketsphinx.pocketsphinx import *
ImportError: No module named pocketsphinx
]

Also I tried the solution given in link:  https://github.com/cmusphinx/pocketsphinx-python/issues/14
but for me its not working

**Comment by nshmyrev** [comment]
Looks like there was some error in installation
