### ISSUE TITLE
Not getting correct output while passing byte array of .wav file  

### ISSUE THREAD

**Issue by dnyanesh-dev-repo** [cmusphinx/pocketsphinx-python#30]
Hi,

I am trying to read wav file and pass that byte array to process_raw() but I didn't get correct output.
If I am using pyaudio for recording and pass that byte array to process_raw() I got correct output.

Please help.
Thanks.

**Comment by nshmyrev** [comment]
Looks like wav audio has wrong format or wrong bandwidth, it should be 16khz 16bit mono. You can share the audio to get help.

**Comment by mbait** [comment]
That's because WAV contains a header. Skip that header and you'll get the
correct result.

**Comment by dnyanesh-dev-repo** [comment]
@nshmyrev 
[arctic_0005.txt](https://github.com/cmusphinx/pocketsphinx-python/files/1115559/arctic_0005.txt)
I changed the file extension .txt due to uploading problem

**Comment by nshmyrev** [comment]
Show your code too.

**Comment by dnyanesh-dev-repo** [comment]
Hi,
@nshmyrev I have attached here my code.
Actually I have created nodejs script  through which I called flask API and pass byte array to that flask API
Also my wav file bandwidth is 16KHz
[code.zip](https://github.com/cmusphinx/pocketsphinx-python/files/1118449/code.zip)

**Comment by nshmyrev** [comment]
Your code is pretty complex, I suggest you to simply if to produce a minimal example demonstrating your problem. https://stackoverflow.com/help/mcve

**Comment by dnyanesh-dev-repo** [comment]
ok sure

**Comment by dnyanesh-dev-repo** [comment]
Hi @nshmyrev ,
I have attached my code here.
[code.py.zip](https://github.com/cmusphinx/pocketsphinx-python/files/1119563/code.py.zip)

**Comment by nshmyrev** [comment]
Ok, and what output do you see? My result here is more or less ok.

**Comment by dnyaneshwar1991** [comment]
When I was saying "demand", it shows "one the", again for "show energy
consumption for one year" = "show one year one".

**Comment by dnyanesh-dev-repo** [comment]
Hi @nshmyrev ,
Here is the output of "show energy consumption tracker weekly data"
![command_output](https://user-images.githubusercontent.com/17723465/27827314-4e57b108-60d4-11e7-8abe-50d28e85bb24.JPG)

**Comment by dnyanesh-dev-repo** [comment]
Hi,
Here is the output for voice taken from mic directly.
![via_mic](https://user-images.githubusercontent.com/17723465/27816776-362a4466-60ab-11e7-8049-ccc9398ccf93.JPG)
