### ISSUE TITLE
ERROR: "model_def_io.c", line 413: Unable to open 

### ISSUE THREAD

**Issue by Kajal1012** [cmusphinx/pocketsphinx-python#31]
hi, 
I am building an acoustic model using link https://cmusphinx.github.io/wiki/tutorialam/  . I am getting following  error while training the model-
ERROR: "model_def_io.c", line 413: Unable to open /home/kajal/ac_mo/model_architecture/ac_mo.1000.mdef for reading: No such file or directory
INFO: senone.c(210): Reading senone mixture weights: /home/kajal/ac_mo/model_parameters/ac_mo.cd_semi_1000_delinterp/mixture_weights
FATAL: "senone.c", line 213: fopen(/home/kajal/ac_mo/model_parameters/ac_mo.cd_semi_1000_delinterp/mixture_weights,rb) failed
Mon Jul 10 09:35:30 2017
Please help

**Comment by nshmyrev** [comment]
Not relevant to pocketsphinx-python, you can get support on forum.
