### ISSUE TITLE
Namespace collision on Debian

### ISSUE THREAD

**Issue by mertyildiran** [cmusphinx/pocketsphinx-python#34]
While I was trying to pack a project for Debian that using `import pocketsphinx` Python module, I realized that there is a **namespace collision** between: 
https://pypi.python.org/pypi/pocketsphinx (source: https://github.com/bambocher/pocketsphinx-python)
and 
https://packages.debian.org/jessie/python/python-pocketsphinx (source: https://github.com/cmusphinx/pocketsphinx/tree/master/swig/python)

Also it's **uncertain** that which one of these projects are the official Python bindings for pocketsphinx:

- https://github.com/cmusphinx/pocketsphinx/tree/master/swig/python

- https://github.com/bambocher/pocketsphinx-python

- https://github.com/cmusphinx/pocketsphinx-python

Please make it clarify and fix this namespace collision.

**Comment by nshmyrev** [comment]
https://github.com/cmusphinx/pocketsphinx/tree/master/swig/python

is a primary source

**Comment by mertyildiran** [comment]
@nshmyrev saying [this is the primary source](https://github.com/cmusphinx/pocketsphinx/tree/master/swig/python) does not solve anything.

You should claim the namespace of https://pypi.python.org/pypi/pocketsphinx Please create a ticket in [here](https://sourceforge.net/p/pypi/support-requests/) with title **Claim package name 'pocketsphinx'**. If you are OK with Dmitry Prazdnichnov then you should talk to him and make the packages identical.

There are packages which are using https://pypi.python.org/pypi/pocketsphinx but unable to proceed through Debian's bureaucracy just because of this namespace collision.
