### ISSUE TITLE
error: package directory 'sphinxbase/swig/python' does not exist

### ISSUE THREAD

**Issue by vlsireddy** [cmusphinx/pocketsphinx-python#36]
Hi,
    i get this error when i try installing pocketsphinx-python.
root@raspberrypi:/home/pi/Documents/voicepi/pocketsphinx-python# python setup.py install
running install
running bdist_egg
running egg_info
writing pocketsphinx.egg-info/PKG-INFO
writing top-level names to pocketsphinx.egg-info/top_level.txt
writing dependency_links to pocketsphinx.egg-info/dependency_links.txt
error: package directory 'sphinxbase/swig/python' does not exist
root@raspberrypi:/home/pi/Documents/voicepi/pocketsphinx-python# 

These are the installations in the same folder

root@raspberrypi:/home/pi/Documents/voicepi# ls -ltr
total 20
drwxr-xr-x 11 root root 4096 Sep  4 20:48 **sphinxbase**
drwxr-xr-x 12 root root 4096 Sep  4 21:02 **pocketsphinx**
-rw-r--r--  1 root root 5777 Sep  4 21:39 stt.py
drwxr-xr-x  7 root root 4096 Sep  4 22:21 **pocketsphinx-python**
root@raspberrypi:/home/pi/Documents/voicepi# 

ensured that all dependencies are installed in first place

Please let me know what is that i am missing.

Thanks

**Comment by nshmyrev** [comment]
sphinxbase should be within pocketsphinx-python, not outside in the same top folder. If you follow the readme and run `git clone --recursive`, it will checkout the proper layout automatically.
