### ISSUE TITLE
No module named pocketsphinx

### ISSUE THREAD

**Issue by pandadao** [cmusphinx/pocketsphinx-python#37]
Excuse me, I had followed your instruction to install the pocketshpinx with $sudo python setup.py install command, and no error message. And pip list has pocketsphinx in the list. But when I run $python example.py, there are some problem with  
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from pocketsphinx.pocketsphinx import *
ImportError: No module named pocketsphinx

I am very comfused about it, Can you give a hand?

**Comment by nshmyrev** [comment]
You need to print sys.path from python to check in what location does it actually look for the module. Then you need to check if module files are actually present in those locations. For details you can check

https://stackoverflow.com/questions/15252040/how-does-python-find-a-module-file-if-the-import-statement-only-contains-the-fil

**Comment by tiancaipipi110** [comment]
@nshmyrev sys.path shows all kinds of path in python dir, such as `C:\\Users\\junew\\AppData\\Roaming\\Python\\Python36\\site-packages `. Then what? Add the path to env variable?

**Comment by nshmyrev** [comment]
Then you need to check if module files are actually present in those locations

**Comment by Sheldon1999** [comment]
having the same issue. installed from instructions given at :
https://github.com/cmusphinx/pocketsphinx-python
OS: Ubuntu 18.04 64-bit
but showing:
```
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    from pocketsphinx.pocketsphinx import *
ModuleNotFoundError: No module named 'pocketsphinx.pocketsphinx'

```
please help..

**Comment by Lukede9** [comment]
> Then you need to check if module files are actually present in those locations

How?
