### ISSUE TITLE
JSGF Grammar

### ISSUE THREAD

**Issue by satell** [cmusphinx/pocketsphinx-python#39]
Hi :) 
I can use now 

config.set_string('-jsgf', 'grammar.gram')

grammar as Language model but it only returns a string with decoder.hyp().hypstr 

how is it possible to make a simple application with grammar like adding two number ? I means semantic parsing with jsgf to return pair values like rule names and matching values ?

thank you very much in advance
Ehsan
thanks for your

**Comment by nshmyrev** [comment]
Not sure what are you asking about
