### ISSUE TITLE
Missing __init__.py after pip installation on Ubuntu 14.04

### ISSUE THREAD

**Issue by marcoesposito1988** [cmusphinx/pocketsphinx-python#4]
Maybe this is intentional, but there is no `__init__.py` file in the "pocketsphinx" and "sphinxbase" directories after installing with pip. This causes an ImportError.

After adding an empty `__init__.py` file in each directory, everything seems to work smoothly.

Am I missing something, or this should be corrected?

**Comment by nshmyrev** [comment]
Yes, we need to upload updated binaries for pip. Sources are fixed already but there is no access to pip unfortunately.
