### ISSUE TITLE
Use path for pulse/pulseaudio.h dependency

### ISSUE THREAD

**Issue by camjac251** [cmusphinx/pocketsphinx-python#40]
Hey

I am trying to install this on a system without root. I have the build tools necessary to build it although I am running into an issue similar to another python package I was installing. It is looking for the pulseaudio dev include files although it's looking system wide instead of my home/user folder where it is located.

```
deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:10: fatal error: pulse/pulseaudio.h: No such file or directory
#include <pulse/pulseaudio.h>
^~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
```

Duplicity is the other script I was using, they have in their setup.py a nice little variable called --librsync-dir
So you could run `python setup.py install --user --librsync-dir=/home/user` and it would use your home path as the root for the include and lib folders, so like so /home/user/include /home/user/bin /home/user/lib64 /home/user/lib. I tried just copying it over from their setup.py into this setup.py but it didn't work for me. [henrysher/duplicity/setup.py](https://github.com/henrysher/duplicity/blob/master/setup.py#L39) is where it is located. Would it be possible to get this to behave the same way in pocketsphinx so those who want to install locally can?

**Comment by kashif3492** [comment]
Just run `sudo apt-get install libpulse-dev` and try again

**Comment by camjac251** [comment]
I do not have root and this isn't a Debian based system

**Comment by cmpunches** [comment]
This dependency fixed it on Fedora 32:

`sudo dnf install pulseaudio-libs-devel`

**Comment by DragonflyRobotics** [comment]
I am running on Ubuntu 20.04 with `sudo` privileges. I also ran the following command:
```sudo apt-get install pulseaudio libpulse-dev```

For some reason, I keep on getting this same error. The only issue I can think of is that I am in a Conda env. What can I do?

**Comment by lenzo-ka** [comment]
This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
