### ISSUE TITLE
using pocketsphinx in a virtual environment

### ISSUE THREAD

**Issue by sharkwheels** [cmusphinx/pocketsphinx-python#41]
Any notes, pointers, or things to be wary about if using this in virtual environment on a Pi3? Any extra steps or particular place to run examples? 

Currently the example can't import any modules. eg:

```
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from pocketsphinx.pocketsphinx import *
ImportError: No module named 'pocketsphinx.pocketsphinx'
```

Installed from github version. Pip refused to install. Thanks!

**Comment by nshmyrev** [comment]
There is extensive documentation how import system works.

https://docs.python.org/3/reference/import.html

To debug python module import you need to figure out where the python module files are actually installed and why python does not see them. It might be a different python version or just PYTHONPATH issue.

**Comment by sharkwheels** [comment]
Has anyone set this up in a virtual environment that you know of?

**Comment by nshmyrev** [comment]
I did
