### ISSUE TITLE
Installing once did not install sphixbase

### ISSUE THREAD

**Issue by bravecorvus** [cmusphinx/pocketsphinx-python#45]
I was building this in the Linux 3.8 distro VM from OSBOXES (on VirtualBox), I noticed that I had to run python setup.py install twice. Installing it just once, I got the error message "cannot find module sphinxbase".

Specifically, here is the bash script I am using to build pocketsphinx-python (and all the dependencies) form source:

```bash
#!/bin/bash
apt update && apt install -y python python-dev python-pip build-essential swig git libpulse-dev bison
sudo -H pip install --upgrade pip && sudo -H pip install setuptools
git clone https://github.com/cmusphinx/sphinxbase.git
cd sphinxbase
./autogen.sh
./configure
make
make check
sudo make install
cd ..
git clone https://github.com/cmusphinx/pocketsphinx.git
cd pocketsphinx
./autogen.sh
./configure
make clean all
make check
sudo make install
cd ..
git clone --recursive https://github.com/cmusphinx/pocketsphinx-python/
cd pocketsphinx-python
sudo -H python setup.py install
sudo python setup.py install
```

Some more information:
OS: OSBoxes Linux Lite 3.8 (a Debian derivative)
Python Version: 2.7.12

Edit: The first time installation also fails to install pocketsphinx.pocketsphinx?

I looked in `pip list`, and pocketsphinx does show up, but importing from `pocketsphinx.pocketsphinx` did not work without the second `sudo python setup.py install` command`

**Comment by nshmyrev** [comment]
You do not need pocketsphinx-python if you install pocketsphinx.
