### ISSUE TITLE
Please clarify the way of importing pocketshinx and sphinxbase modules in example.py

### ISSUE THREAD

**Issue by blvckcrxw** [cmusphinx/pocketsphinx-python#49]
I see here the whole bunch of issues addressing problem of importing pocketsphinx and sphinxbase modules to readme example. And yet i didn't see any answer helping me to solve this problem.
I got properly installed modules of sphinxbase and pocketsphinx and I add path to them via sys.path.append('/usr/local/lib/python2.7/dist-packeges') but this doesn`t seem to help.

I hope smb gives an explanation over this problem finally

**Comment by nshmyrev** [comment]
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
