### ISSUE TITLE
Having issues with the new .lm.bin

### ISSUE THREAD

**Issue by valiantone** [cmusphinx/pocketsphinx-python#5]
ERROR: "ngram_model_dmp.c", line 121: Wrong magic header size number 54726965: pocketsphinx/model/en-us/en-us.lm.bin is not a dump file

have no idea to get down to this, any help would be appreciated, and this is just with running the example.

**Comment by nshmyrev** [comment]
Update pocketsphinx, bin files are supported in the latest versions only. For more details check our website.
