### ISSUE TITLE
How to print phoneme sequence?

### ISSUE THREAD

**Issue by David-webb** [cmusphinx/pocketsphinx-python#52]
I didn't find the 'en-us-phone.lm.bin' model file in directory 'pocketsphix/model/', and i tried " config.set_string('-allphone', 'model/en-us/en-us-phone.lm.bin'  " , and it didn't work. I got "RuntimeError: new_Decoder returned -1"

**Comment by nshmyrev** [comment]
You can use `find` command to search for files, the file is there:

https://github.com/cmusphinx/pocketsphinx/tree/master/model/en-us
