### ISSUE TITLE
how do i trained tidigits acoustic model with my own audiofiles? missing mixture_weights file in the acoustic tidigits model.

### ISSUE THREAD

**Issue by MuruganR96** [cmusphinx/pocketsphinx-python#53]
how can i trained tidigits acoustic model with my own audiofiles? 
missing **mixture_weights** file in the acoustic tidigits model.

i was tried to train my own accent audios for digits using cmu pocketsphinx.
i was struggled lot, in this part. no such file **mixture_weights**

> ./map_adapt \
>     -moddeffn tidigits/hmm/mdef.txt \
>     -ts2cbfn .cont. \
>     -meanfn tidigits/hmm/means \
>     -varfntidigits/hmm/variances \
>     -mixwfn tidigits/hmm/mixture_weights \
>     -tmatfn tidigits/hmm/transition_matrices \
>     -accumdir . \
>     -mapmeanfn en_in_own/means \
>     -mapvarfn en_in_own/variances \
>     -mapmixwfn en_in_own/mixture_weights \
>     -maptmatfn en_in_own/transition_matrices

```
sphinx_fe -argfile tidigits/hmm/feat.params -samprate 16000 -c digits.fileids -di . -do . -ei wav -eo mfc -mswav yes

pocketsphinx_mdef_convert -text tidigits/hmm/mdef tidigits/hmm/mdef.txt

cp -a /usr/local/libexec/sphinxtrain/bw .
cp -a /usr/local/libexec/sphinxtrain/mk_s2sendump .
cp -a /usr/local/libexec/sphinxtrain/map_adapt .
cp -a /usr/local/libexec/sphinxtrain/mllr_solve .

./bw \
 -hmmdir tidigits/hmm \
 -moddeffn tidigits/hmm/mdef.txt \
 -ts2cbfn .cont. \
 -feat 1s_c_d_dd \
 -cmn current \
 -agc none \
 -dictfn tidigits.dic \
 -ctlfn digits.fileids \
 -lsnfn digits.transcription \
 -accumdir .

./mllr_solve \
    -meanfn tidigits/hmm/means \
    -varfn tidigits/hmm/variances \
    -outmllrfn mllr_matrix -accumdir .

mkdir en_in_own
cp -a tidigits/hmm/ en_in_own
```
how to i resolve this issue. and then how to train with my own accent besed digits audios.
help me sir. i am begginer for this concept.

Thanks.

**Comment by nshmyrev** [comment]
This is a wrong place to ask this question. Ask on sourceforge forum.
