### ISSUE TITLE
new_Decoder returned -1 when Unicode character on project path

### ISSUE THREAD

**Issue by csasia** [cmusphinx/pocketsphinx-python#55]
When the project's path contains a Unicode character ("C:\Users\Camilo\Proyectos\Python\\**Transcripción** de audio"), I get the following error:

`File "C:\Users\Camilo\Proyectos\Python\Transcripción de audio\env\lib\site-packages\pocketsphinx\pocketsphinx.py", line 276, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1`

I think the issue could be in the __pocketsphinx.cp37-win_amd64.pyd_ file.

**Comment by lenzo-ka** [comment]
This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
