### ISSUE TITLE
Decoding with other acoustic models

### ISSUE THREAD

**Issue by aweitz** [cmusphinx/pocketsphinx-python#56]
Hi, can you clarify if is it possible using pocketsphinx to decode explicit phoneme sequences (generated separately with my own acoustic model) into a sequence of words? It seems the Decoder must be mapping phonemes to words at some point, but it's not clear to me if there is a standalone function to do this. My acoustic model outputs 39 english phonemes, so I would like to use the provided language model and dictionary. Thanks.

**Comment by nshmyrev** [comment]
> Hi, can you clarify if is it possible using pocketsphinx to decode explicit phoneme sequences (generated separately with my own acoustic model) into a sequence of words?

No, there is nothing like it here.

> It seems the Decoder must be mapping phonemes to words at some point, but it's not clear to me if there is a standalone function to do this. 

No, it does not work like that. See http://cmusphinx.github.io/wiki/tutorialconcepts.
