### ISSUE TITLE
This repository is 120 commits behind bambocher

### ISSUE THREAD

**Issue by aaronchantrill** [cmusphinx/pocketsphinx-python#64]
I was assuming that this was the official pocketsphinx-python repository and was confused why it was so different than the documentation on PyPi. PyPi reports the home of their hosted pocketsphinx-python as https://github.com/bombocher/pocketsphinx-python. That repository is version 0.1.15 while this is 0.0.9. This repository is a fork of that one and is 108 commits behind and 8 ahead of that project.

So it seems like bombocher/pocketsphinx-python is the repository I should refer people to git clone for the latest developments.

I'm curious why this repository hasn't pulled code from the parent repository in such a long time and what the status of both projects is. I assume you are just too busy at the moment to worry about such details.

Thank you for all you do.

**Comment by nshmyrev** [comment]
> So it seems like bombocher/pocketsphinx-python is the repository I should refer people to git clone for the latest developments.

You should be referring https://github.com/alphacep/vosk-api
