### ISSUE TITLE
Not able to install pocketsphinx

### ISSUE THREAD

**Issue by nag0811** [cmusphinx/pocketsphinx-python#65]
Hi, 
   I am not able to install package using python. I am getting following error. I have downloaded swig files and copied to python installation folder as explained in <https://stackoverflow.com/questions/44504899/installing-pocketsphinx-python-module-command-swig-exe-failed> Still I got the following issue. 

Python version is : 3.7.7

(base) C:\Users\nb185041>pip install pocketsphinx
Collecting pocketsphinx
  Using cached pocketsphinx-0.1.15.tar.gz (29.1 MB)
Building wheels for collected packages: pocketsphinx
  Building wheel for pocketsphinx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nb185041\\AppData\\Local\\Temp\\pip-install-rr5rbpnx\\pocketsphinx\\setup.py'"'"'; __file__='"'"'C:\\Users\\nb185041\\AppData\\Local\\Temp\\pip-install-rr5rbpnx\\pocketsphinx\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\nb185041\AppData\Local\Temp\pip-wheel-svgsjrur'
       cwd: C:\Users\nb185041\AppData\Local\Temp\pip-install-rr5rbpnx\pocketsphinx\
  Complete output (29 lines):
  running bdist_wheel
  running build_ext
  building 'sphinxbase._sphinxbase' extension
  swigging deps/sphinxbase/swig/sphinxbase.i to deps/sphinxbase/swig/sphinxbase_wrap.c
  C:\ProgramData\Anaconda3\swig.exe -python -modern -threads -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o deps/sphinxbase/swig/sphinxbase_wrap.c deps/sphinxbase/swig/sphinxbase.i
  creating build
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\deps
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\lm
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\feat
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\util
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\fe
  creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\swig
  C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include -c deps/sphinxbase/src/libsphinxbase/lm\fsg_model.c -o build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\lm\fsg_model.o /wd4244 /wd4267 /wd4197 /wd4090 /wd4018 /wd4311 /wd4312 /wd4334 /wd4477 /wd4996
  gcc: error: /wd4244: No such file or directory
  gcc: error: /wd4267: No such file or directory
  gcc: error: /wd4197: No such file or directory
  gcc: error: /wd4090: No such file or directory
  gcc: error: /wd4018: No such file or directory
  gcc: error: /wd4311: No such file or directory
  gcc: error: /wd4312: No such file or directory
  gcc: error: /wd4334: No such file or directory
  gcc: error: /wd4477: No such file or directory
  gcc: error: /wd4996: No such file or directory
  error: command 'C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pocketsphinx
  Running setup.py clean for pocketsphinx
Failed to build pocketsphinx
Installing collected packages: pocketsphinx
    Running setup.py install for pocketsphinx ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nb185041\\AppData\\Local\\Temp\\pip-install-rr5rbpnx\\pocketsphinx\\setup.py'"'"'; __file__='"'"'C:\\Users\\nb185041\\AppData\\Local\\Temp\\pip-install-rr5rbpnx\\pocketsphinx\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nb185041\AppData\Local\Temp\pip-record-x5dl9nb2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\programdata\anaconda3\Include\pocketsphinx'
         cwd: C:\Users\nb185041\AppData\Local\Temp\pip-install-rr5rbpnx\pocketsphinx\
    Complete output (29 lines):
    running install
    running build_ext
    building 'sphinxbase._sphinxbase' extension
    swigging deps/sphinxbase/swig/sphinxbase.i to deps/sphinxbase/swig/sphinxbase_wrap.c
    C:\ProgramData\Anaconda3\swig.exe -python -modern -threads -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ideps/sphinxbase/swig -outdir sphinxbase -o deps/sphinxbase/swig/sphinxbase_wrap.c deps/sphinxbase/swig/sphinxbase.i
    creating build
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\deps
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\lm
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\feat
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\util
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\fe
    creating build\temp.win-amd64-3.7\Release\deps\sphinxbase\swig
    C:\ProgramData\Anaconda3\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/win32 -Ic:\programdata\anaconda3\include -Ic:\programdata\anaconda3\include -c deps/sphinxbase/src/libsphinxbase/lm\fsg_model.c -o build\temp.win-amd64-3.7\Release\deps\sphinxbase\src\libsphinxbase\lm\fsg_model.o /wd4244 /wd4267 /wd4197 /wd4090 /wd4018 /wd4311 /wd4312 /wd4334 /wd4477 /wd4996
    gcc: error: /wd4244: No such file or directory
    gcc: error: /wd4267: No such file or directory
    gcc: error: /wd4197: No such file or directory
    gcc: error: /wd4090: No such file or directory
    gcc: error: /wd4018: No such file or directory
    gcc: error: /wd4311: No such file or directory
    gcc: error: /wd4312: No such file or directory
    gcc: error: /wd4334: No such file or directory
    gcc: error: /wd4477: No such file or directory
    gcc: error: /wd4996: No such file or directory
    error: command 'C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\programdata\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nb185041\\AppData\\Local\\Temp\\pip-install-rr5rbpnx\\pocketsphinx\\setup.py'"'"'; __file__='"'"'C:\\Users\\nb185041\\AppData\\Local\\Temp\\pip-install-rr5rbpnx\\pocketsphinx\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nb185041\AppData\Local\Temp\pip-record-x5dl9nb2\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\programdata\anaconda3\Include\pocketsphinx' Check the logs for full command output.

(base) C:\Users\nb185041>

**Comment by AdrianNicoli** [comment]
I finally figured this out. I tried many different solutions, and finally stumbled upon this https://anaconda.org/conda-forge/pocketsphinx-python, so I run the following command with conda, and got this result. 
```
$ conda install -c conda-forge pocketsphinx-python
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): \ done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                                                        

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pocketsphinx-python -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

I then created a virtual environment with python version 3.6, and I managed to pip install pocketsphinx without issues.

**Comment by lenzo-ka** [comment]
This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
