### ISSUE TITLE
'Decoder' is not defined when running example.py

### ISSUE THREAD

**Issue by sidja** [cmusphinx/pocketsphinx-python#7]
Am I missing something ?  I get the following message

```
 Traceback (most recent call last):
 File "example.py", line 10, in <module>
 config = Decoder.default_config()
 NameError: name 'Decoder' is not defined
```

**Comment by nshmyrev** [comment]
You are missing the import of pocketsphinx module in the beginning of the python file.

**Comment by sidja** [comment]
I've included import files 

```
 from pocketsphinx.pocketsphinx import *
 from sphinxbase.sphinxbase import *
```

Now I get the following error message 

```
Traceback (most recent call last):
File "example.py", line 3, in <module>
from pocketsphinx.pocketsphinx import *
ImportError: No module named pocketsphinx
```

**Comment by nshmyrev** [comment]
So this error is pretty self-explaining. You do not have pocketsphinx module installed properly. You can follow installation manual to get it installed.

**Comment by sidja** [comment]
Great, thank you for that. It works now. I didn't realise that both the module had to be installed manually first

**Comment by lsvannur** [comment]
hey , can u please give me  the guidance  how you solved your installation problem i am struck in installing those packages. iam also getting same errors as above
