### ISSUE TITLE
Understand 'no_search' and 'full_utt' parameters

### ISSUE THREAD

**Issue by davidepietrasanta** [cmusphinx/pocketsphinx-python#73]
I know the following parameters exist:

- `no_search`: False (default)
- `full_utt`: False (default)

Unfortunately, even browsing the code and the documentation I cannot understand what they control and what they are for.

**Comment by lenzo-ka** [comment]
This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
