### ISSUE TITLE
Should we be now using this branch?

### ISSUE THREAD

**Issue by sthibaul** [cmusphinx/pocketsphinx-python#74]
Hello,

https://github.com/cmusphinx/pocketsphinx-python is shown by github as being forked from bambocher/pocketsphinx-python, are we supposed to consider that development now happens here rather than there? There are quite a few bug reports there that are probably worth looking at.

Samuel

**Comment by lenzo-ka** [comment]
Development is moving to pocketsphinx -- thanks!

This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
