### ISSUE TITLE
testsuite failure on i386

### ISSUE THREAD

**Issue by sthibaul** [cmusphinx/pocketsphinx-python#75]
(ported from https://github.com/bambocher/pocketsphinx-python/issues/52)

Hello,

The testsuite seems to be failing on i386:
https://buildd.debian.org/status/fetch.php?pkg=pocketsphinx-python&arch=i386&ver=1%3A0.1.15-1&stamp=1584846130&raw=0

I can confirm that this is still the case with the latest checkout of pocketsphinx-python.

Samuel

**Comment by lenzo-ka** [comment]
This module is obsolete; python bindings are now in [pocketsphinx](https://github.com/cmusphinx/pocketsphinx)
