### ISSUE TITLE
Is it possible to get timestamps for starting and ending of words  with the following setup ? 

### ISSUE THREAD

**Issue by sidja** [cmusphinx/pocketsphinx-python#8]
According to the help menu in pocketspinx_continous the time option describes  " Print word times in file transcription."

I've tried to include the following in the decoder config. I am not sure if I am doing it right. 

```
 config.set_string('-time', 'time.txt')
 decoder = Decoder(config)
```

**Comment by nshmyrev** [comment]
This options works only in `pocketsphinx_continuous` and is irrelevant for Python.

To print words and their times in Python you can use

```
print ('Best hypothesis segments: ', decoder.seg())
```

You can find more examples in https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/decoder_test.py

**Comment by charlielaud** [comment]
Hey nshmyrev,

How _do_ you properly call the time option? I'm trying to call it from the command line as such:
`$ pocketsphinx_continuous -time -infile testFile.wav > textDump.txt`

But I have no idea what arguments I'm supposed to pass to make that work. Any idea?

Thanks!

**Comment by nshmyrev** [comment]
pocketsphinx_continuous -time yes -infile testFile.wav > textDump.txt
