### ISSUE TITLE
Live streaming with python

### ISSUE THREAD

**Issue by cfwelch** [cmusphinx/pocketsphinx-python#9]
Can you help me figure out how to live stream mic input into the python program? I'm trying to figure out if I can use gstreamer somehow with the example.py but I'm having a hard time.

Thanks

**Comment by nshmyrev** [comment]
https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/kws_test.py

contains pyaudio example.

**Comment by cfwelch** [comment]
Hi,

Thanks for the example. I've tried to run this and it gets to a point where it is just outputting things like this:

INFO: cmn_prior.c(116): cmn_prior_update: to   < 60.80 -9.63 15.42 24.64 -11.65 22.93 -0.86 -14.32 -4.19 -28.97 -22.39 -29.66 -30.96 >
INFO: cmn_prior.c(99): cmn_prior_update: from < 60.80 -9.63 15.42 24.64 -11.65 22.93 -0.86 -14.32 -4.19 -28.97 -22.39 -29.66 -30.96 >
INFO: cmn_prior.c(116): cmn_prior_update: to   < 63.61 -10.68 17.65 27.64 -14.80 29.81 -6.41 -10.70 -4.91 -33.42 -20.50 -34.30 -30.04 >

and it never outputs a hypothesis. Do you know why this might be happening?

Thanks again,
Charlie

**Comment by nshmyrev** [comment]
You can add -rawlogdir &lt;dir&gt; to configuration to dump raw files. You can listen them to get an idea what is being recorded. 

Most likely audio format is wrong, something like big endian instead of little endian or wrong sample rate.

**Comment by sajith91** [comment]
hi , I know this an old question. But i want to know how to do " add -rawlogdir <dir> to configuration to dump raw files" which you have mentioned above.
